//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interventie
    {
        public int InterventieID { get; set; }
        public int MedicID { get; set; }
        public int PacientID { get; set; }
        public int TipInterventieID { get; set; }
        public System.DateTime DataOra { get; set; }
        public int PretID { get; set; }
    
        public virtual Medic Medic { get; set; }
        public virtual Pacient Pacient { get; set; }
        public virtual Pret Pret { get; set; }
        public virtual TipIntervenie TipIntervenie { get; set; }
    }
}
