//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pret
    {
        public Pret()
        {
            this.Interventie = new HashSet<Interventie>();
        }
    
        public int PretID { get; set; }
        public int TipInterventieID { get; set; }
        public System.DateTime DataInceput { get; set; }
        public System.DateTime DataSfarsit { get; set; }
        public decimal Pret1 { get; set; }
    
        public virtual ICollection<Interventie> Interventie { get; set; }
        public virtual TipIntervenie TipIntervenie { get; set; }
    }
}
